// FALLBACK pegawai — dijana oleh scripts/sync-penugasan.ts daripada xlsx rasmi.
// Hanya medan SELAMAT-AWAM (tiada IC, tiada telefon, tiada foto) + penugasan masjid.
// Jalankan: npm run sync:penugasan
// Jumlah rekod: 93

export type KategoriPegawai = "ketua-imam" | "timbalan-ketua-imam" | "bilal";

export const kategoriLabel: Record<KategoriPegawai, string> = {
  "ketua-imam": "Ketua Imam",
  "timbalan-ketua-imam": "Timbalan Ketua Imam",
  bilal: "Bilal",
};

export type PegawaiPublic = {
  employeeNo: string;
  nama: string;
  kategori: KategoriPegawai;
  jawatanPenuh: string;
  emelRasmi: string;
  gred: string;
  masjidNama?: string;
  masjidZonNombor?: number;
  masjidZonNama?: string;
};

export const pegawaiFallback: PegawaiPublic[] = [
  { employeeNo: "0033", nama: "Helmy bin Yahya", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam", emelRasmi: "helmy@maiwp.gov.my", gred: "S10", masjidNama: "Masjid Al-Mubarakah", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1991", nama: "Abdul Hanif bin Abdul Latif", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "abdulhaniflatif@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Hidayah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1909", nama: "Ahmad Faiz bin Hj Mustapa", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "ahmadfaiz@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Abu Hurairah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1768", nama: "Ahmad Rizwan Nazhif bin Zainol Ariffin", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "ahmadrizwan@maiwp.gov.my", gred: "S1", masjidNama: "Surau Istana Negara (Lama)", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "2062", nama: "Ahmad Shazril Amri bin Mohammad Shiham", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "shazrilamri@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Jamek Tengku Abdul Aziz Shah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1683", nama: "Azli bin Ibrahim", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "azli@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Jamek Sultan Abdul Samad", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1746", nama: "Firdaus bin Ahmad", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam", emelRasmi: "firdausahmad@maiwp.gov.my", gred: "S1", masjidNama: "Masjid At-Taqwa", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1738", nama: "Hamzah bin Akmal Hisham", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "hamzah.akmal@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Saidina Othman Ibnu Affan", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1741", nama: "Mohamad Hasbi bin Md Akip", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "mohamad.hasbi@maiwp.gov.my", gred: "S1", masjidNama: "Surau Utama Istana Negara", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "1733", nama: "Mohamad Napiri bin Hasan", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "napiri@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Anas Bin Malik", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1779", nama: "Mohamad Sayuti bin Jalaluddin", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "sayuti@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Mubarakah", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1742", nama: "Mohd Khairul Ni'mat bin Doll Kawaid", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "nimat@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Saidina Ali KW", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1973", nama: "Mohd Nabil bin Laita Affandi", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "mohdnabillaita@maiwp.gov.my", gred: "S1", masjidNama: "Surau Utama Istana Negara", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "1778", nama: "Mohd Safwan bin Abd Rahman", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "mohd.safwan@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Talhah bin Ubaidillah", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1735", nama: "Mohd Yasien bin Ramli", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "mohdyasien@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Abdullah bin Zubair", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1889", nama: "Muhammad Azan bin Abd Malek", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "azanmalek@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Mukhlisin (Alam Damai)", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1722", nama: "Muhammad Farhan bin Wahab", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "muhammadfarhan@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Firdaus", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1972", nama: "Muhammad Haikal bin Zaini", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "haikalzaini@maiwp.gov.my", gred: "S1", masjidNama: "Surau Utama Istana Negara", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "1880", nama: "Muhammad Hakim bin Abd Malek", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "m.hakim@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Muttaqin", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1813", nama: "Muhammad Haziq Sulhi bin Chek", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "haziqsulhi@maiwp.gov.my", gred: "S1", masjidNama: "Masjid As-Sodiqin", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1766", nama: "Muhammad Iqbal bin Md Said", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "miqbal@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Usamah bin Zaid", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1788", nama: "Muhammad Izzuddin bin Ikhsan", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "izzuddin@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Asy-Syakirin", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1988", nama: "Muhammad Izzul bin Zamani", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "izzulzamani@maiwp.gov.my", gred: "S1", masjidNama: "Surau Utama Istana Negara", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "1723", nama: "Muhammad Najib bin Mohd Razali", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "najibrazali@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Ibn Mas'ud", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1821", nama: "Muhammad Nur Izzat bin Roshidi", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam", emelRasmi: "izzatroshidi@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Jamek Layang-Layangan", masjidZonNombor: 8, masjidZonNama: "Zon 8 — WP Labuan" },
  { employeeNo: "1767", nama: "Muhammad Safuan bin Adnan", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "safuanadnan@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Solehin", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1989", nama: "Muhammad Shafiq Muaddib bin Harun", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "shafiqmuaddib@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Imam Ash-Shafie", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1730", nama: "Muhammad Syafiq bin Zulkarnain", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "muhammadsyafiq@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Al-Hidayah (Sentul)", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "2051", nama: "Syaarif bin Shafie", kategori: "bilal", jawatanPenuh: "Pembantu Hal Ehwal Islam (Bilal)", emelRasmi: "syaarif@maiwp.gov.my", gred: "S1", masjidNama: "Masjid Jamek Al-Khadijiah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1694", nama: "Abu Bakar bin Mohamad Noor", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "abubakar@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Mahmoodiah", masjidZonNombor: 7, masjidZonNama: "Zon 7 — WP Putrajaya" },
  { employeeNo: "1714", nama: "Adam bin Abd Rashid", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "adamrashid@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Amaniah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1695", nama: "Ahmad Ammar Muzakir bin Ahmad Hadiri", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "muzakir@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Muqarrabin", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1709", nama: "Ahmad Faidhul Irfan bin Ahmad Mustaffa Kamal", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "ahmadfaidhul@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Abu Ubaidah Al-Jarrah", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1978", nama: "Ahmad Fakhruddin bin Mohd Tahir", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "fakhruddin@maiwp.gov.my", gred: "S9", masjidNama: "Masjid At-Taqwa", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1732", nama: "Amirul Hafiz bin Gadimin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "amirulhafiz@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Saidina Othman Ibnu Affan", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1739", nama: "Andi Mohamad Zulkhairi bin Muhamad", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "andi@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Saidina Umar Al-Khattab", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1704", nama: "Hasan Basri bin Soidin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "hasan.basri@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Zaid bin Haritsah", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1697", nama: "Ibnuzzaman bin Hasan", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "ibnuzzaman@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Jamek Abdullah Hukum Eco City", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1852", nama: "Mior Ahmad Fitri bin Mior Shahridan", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "ahmadfitri@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Jamek Saad Ibn Waqqas", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1701", nama: "Mohamad Faiz bin Sapiee @ Abd. Razak", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "faiz@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Najihin", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1712", nama: "Mohamad Syamim bin Mohd Hussin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "syamim@maiwp.gov.my", gred: "S9", masjidNama: "Ibu Pejabat MAIWP", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "2109", nama: "Mohammad Allif bin Justin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam", emelRasmi: "allifjustin@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Jamek Layang-Layangan", masjidZonNombor: 8, masjidZonNama: "Zon 8 — WP Labuan" },
  { employeeNo: "1736", nama: "Mohd Afiq Izzudin bin Abdul Hamid", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "afiqizzudin@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Ubudiah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "0896", nama: "Mohd Noor Ihsan bin Kamaruzaman", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam", emelRasmi: "noor.ihsan@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Bilal bin Rabah", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1713", nama: "Mohd Shahrulnizam bin Md Yusof", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "nizamyusof@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Akram", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1715", nama: "Muhamad Ali Fikri bin Zainudin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "alifikri@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Zaid bin Thabit", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1703", nama: "Muhammad Amin Firdaus bin Sabudin", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "aminfirdaus@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Jamek Al-Khadijiah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1711", nama: "Muhammad Ansari bin Paslan", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "ansari@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Saidina Abu Bakar As-Siddiq", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1875", nama: "Muhammad Fauzan bin Mohd Dahlan", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "fauzan@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Imam Al-Ghazali", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1727", nama: "Muhammad Fauzie bin Bashah", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "fauziebashah@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Ibnu Sina", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1700", nama: "Muhammad Husaini bin Harun", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "husainiharun@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Muadz bin Jabal", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1710", nama: "Muhammad Mun'aim bin Jaafar", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "munaim@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Khasyi'in", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1743", nama: "Muhammad Rashidi bin Ab Hamid", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "rashidi@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Solehin", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1734", nama: "Muhammad Syarifuddin bin Mohd Lotfi", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "msyarifuddin@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Abdul Rahman bin Auf", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1705", nama: "Nur Mahadi bin Baharum", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam", emelRasmi: "mahadi@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Jamek An-Nur", masjidZonNombor: 8, masjidZonNama: "Zon 8 — WP Labuan" },
  { employeeNo: "1748", nama: "Wan Abdul Halim bin Md Yusoff", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "wanabdulhalim@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Talhah bin Ubaidillah", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1465", nama: "Wan Mohamad Amzar Fitri bin Wan Mohd Azlan", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "amzar@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Bukit Aman", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1747", nama: "Wan Mohd Rahim bin Wan Yusoff", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "wanmohdrahim@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Ikhlasiah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "0281", nama: "Zulkifle bin Jusoh", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "zulkifle@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Qurtubi", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "0340", nama: "Zulkifli bin Mohamad", kategori: "ketua-imam", jawatanPenuh: "Pegawai Hal Ehwal Islam (Ketua Imam)", emelRasmi: "zulkifli.mohamad@maiwp.gov.my", gred: "S9", masjidNama: "Masjid Al-Muhsinin", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1803", nama: "Amirul Syahmee bin Amir Hamzah", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "syahmee@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Salahuddin Al-Ayyubi", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1692", nama: "Anuar bin Mat Saad", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam", emelRasmi: "anuar@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Sultan Abdullah", masjidZonNombor: 8, masjidZonNama: "Zon 8 — WP Labuan" },
  { employeeNo: "1847", nama: "Kamarul Azzely bin Mohamad Kamal", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "kamarul.azzely@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Amaniah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1811", nama: "Khairul Hafizin bin Ahmad", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hafizin@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Imam At-Tirmizi", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1717", nama: "Mohamad Norfirdaus bin Azman", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "norfirdaus@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Amru bin Al-'As", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "1686", nama: "Mohamad Nur Arif bin Rosli", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "arif.rosli@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Ibn Mas'ud", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1729", nama: "Mohamad Zu Arif Billah bin Mohamad Pauzi", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "zuarif@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Akram", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1810", nama: "Mohammad Hanif Syakir bin Mohd Yusoop", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hanifsyakir@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Jamek Alam Shah", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1708", nama: "Mohammad Talhah bin Alimin @ Ab Aziz", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "mohammadtalhah@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Ikhlasiah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "1744", nama: "Mohd Aqil bin Mohd Ghazali", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "mohd.aqil@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Bukit Aman", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1745", nama: "Mohd Arifin bin Zulkaplay", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "mohdarifin@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Ubudiah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1802", nama: "Mohd Azam bin Md Isa", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "azam.mdisa@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Abdullah bin Zubair", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1707", nama: "Muhamad Afiq bin Hamzah", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "muhamad.afiq@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Abu Hurairah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1997", nama: "Muhamad Amirzakiudin bin Nuzam", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "amirzakiudin@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Nurul Islam", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1770", nama: "Muhamad Hanafi bin Wahid", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hanafiwahid@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Jamek Ibnu Khaldun", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1822", nama: "Muhammad Ainul Hariz bin Abu Hassan", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "ainulhariz@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Jamek Kampung Baru", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1690", nama: "Muhammad Amirul bin Ismail", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "amirul.ismail@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Jamek Al-Khadijiah", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
  { employeeNo: "2060", nama: "Muhammad Azad bin Abdul Aziz", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "azad@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Zaid bin Haritsah", masjidZonNombor: 2, masjidZonNama: "Zon 2 — Sentul / Gombak / Setapak" },
  { employeeNo: "2048", nama: "Muhammad Danish Farhan bin Mohd Faizal", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "danish@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Usamah bin Zaid", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1689", nama: "Muhammad Hafifi bin Hamdan", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hafifi@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Muhammad Al-Fateh", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1800", nama: "Muhammad Hanif bin Khairol Annuar", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hanif.khairol@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Abu Ubaidah Al-Jarrah", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1962", nama: "Muhammad Hasanuddin bin Abdullah", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "hasanuddin@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Saidina Hamzah", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "2115", nama: "Muhammad Ikhwan Hafiz bin Johari", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "ikhwanhafiz@maiwp.gov.my", gred: "S5", masjidNama: "Surau Istana Negara (Lama)", masjidZonNombor: 9, masjidZonNama: "Posting Khas — Istana Negara / Ibu Pejabat MAIWP" },
  { employeeNo: "2089", nama: "Muhammad Khalil bin Ramli", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "khalil@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Zakirin", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1685", nama: "Muhammad Nizam bin Razali", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "nizamrazali@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Saidina Othman Ibnu Affan", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1804", nama: "Muhammad Syammir Izzuddin bin Shamsuddin", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "syammir@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Zaid bin Thabit", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1961", nama: "Muhammad Taqiuddin bin Sulaiman", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "taqiuddin@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Khalid bin Al-Walid", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "2126", nama: "Muhammad Zaid bin Zulkhairi", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "zaid@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Mukhlisin", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1809", nama: "Naufal bin Mahpuzillah", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "naufal@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Asy-Syakirin", masjidZonNombor: 3, masjidZonNama: "Zon 3 — Bandar / Kampung Baru / Kampung Pandan" },
  { employeeNo: "1728", nama: "Nik Muhammad Fadlan bin Nik Mahmood", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "nikfadlan@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Talhah bin Ubaidillah", masjidZonNombor: 5, masjidZonNama: "Zon 5 — Sri Petaling / Bandar Tun Razak / Cheras Selatan / Sungai Besi" },
  { employeeNo: "1740", nama: "Shafiq Zulkhairi bin Zainudin", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "zulkhairi@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Muttaqin", masjidZonNombor: 4, masjidZonNama: "Zon 4 — Keramat / Setiawangsa / Titiwangsa / Wangsa Maju" },
  { employeeNo: "1678", nama: "Shahrulnizam bin Shah Peri", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "shahrulnizam@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Al-Imam Al-Ghazali", masjidZonNombor: 1, masjidZonNama: "Zon 1 — Kepong / Batu / Segambut" },
  { employeeNo: "1993", nama: "Wan Noor Muhammad Hakim bin Wan Din", kategori: "timbalan-ketua-imam", jawatanPenuh: "Penolong Pegawai Hal Ehwal Islam (Timbalan Ketua Imam)", emelRasmi: "wannoorhakim@maiwp.gov.my", gred: "S5", masjidNama: "Masjid Ar-Rahman", masjidZonNombor: 6, masjidZonNama: "Zon 6 — Bangsar / Lembah Pantai / TTDI / Bukit Damansara" },
];
