/* Slaid "Kursus Intensif Pengurusan Jenazah Wilayah Persekutuan" — modul PERKIB.
   Setiap slaid dirender daripada deck asal (1920×1080 → webp 2560px) supaya
   paparan KEKAL SAMA seperti fail asal. Latar, transisi, zoom dan grid ialah
   pembalut sahaja — kandungan slaid tidak diubah.

   TAJUK dijana automatik daripada deck sumber (heading → teks terbesar → label);
   digunakan untuk grid lompat slaid, teks alt dan pembaca skrin. */

export const SLIDE_COUNT = 131;

export const TAJUK: string[] = [
  "KURSUS INTENSIF PENGURUSAN JENAZAH WILAYAH PERSEKUTUAN",
  "HUKUM",
  "4 KEWAJIPAN DALAM MENGURUSKAN JENAZAH",
  "MANDI JENAZAH",
  "HUKUM",
  "SYARAT KEUTAMAAN PEMANDI JENAZAH",
  "SYARAT TEMPAT MANDI JENAZAH",
  "ALATAN MANDIAN",
  "SYARAT PEMANDI JENAZAH",
  "SYARAT PEMANDI JENAZAH",
  "HUKUM MANDI MAHRAM JANTINA BERBEZA",
  "TURUTAN PEMANDI LEBIH AFDAL",
  "Imam Al-Nawawi dalam syarahan beliau ke atas kenyataan Al-Shirazi di atas",
  "MENJAGA AIB JENAZAH",
  "AURAT JENAZAH",
  "Sunan Abi Dawud 3141",
  "WAJIB menutup aurat jenazah.",
  "TATACARA MEMANDIKAN JENAZAH",
  "Zainab binti Muhammad.",
  "TATACARA MEMANDIKAN JENAZAH",
  "TATACARA MEMANDIKAN JENAZAH",
  "TATACARA MEMANDIKAN JENAZAH",
  "TATACARA MEMANDIKAN JENAZAH",
  "TAYAMMUM",
  "JENAZAH SYAHID",
  "MATI DALAM IHRAM",
  "Rajah · Mandi Jenazah",
  "TATACARA PENGURUSAN JANIN DAN BAYI GUGUR",
  "Jika janin belum kelihatan bentuk lembaga",
  "NAJIS KELUAR SELEPAS DIMANDIKAN",
  "KAFAN JENAZAH",
  "HUKUM DAN TANGGUNGJAWAB KAFAN",
  "KISAH MUS'AB",
  "Mus'ab bin 'Umair",
  "PENGAJARAN HADIS MUS'AB",
  "JUMLAH KAIN KAFAN (LELAKI)",
  "Sebab itu yang paling afdal menurut Mazhab Syafi’i ialah:",
  "JUMLAH KAIN KAFAN - PEREMPUAN",
  "Sunan Abi Dawud 3157",
  "JUMLAH KAIN KAFAN",
  "WARNA KAIN KAFAN",
  "Dalam konteks hadis ini mempunyai dua topik yang berbeza:",
  "ALATAN UNTUK KAFANKAN JENAZAH",
  "CARA KAFANKAN JENAZAH",
  "PENYEDIAAN PROSES KAFAN",
  "PENYEDIAAN PROSES KAFAN",
  "PENYEDIAAN PROSES KAFAN",
  "KESEDERHANAAN DALAM KAFAN JENAZAH -KISAH ABU BAKAR",
  "Dengan tiga helai kain putih sahuliyyah",
  "HIKMAH HADIS",
  "KEKELIRUAN DALAM PENGURUSAN JENAZAH",
  "HUKUM MENCIUM JENAZAH",
  "SOLAT JENAZAH",
  "satu jenazah untuk Baginda solatkan. Lalu Baginda bertanya: \"Adakah si mati",
  "Hadis ini menunjukkan bahawa:",
  "SOLAT JENAZAH BERJEMAAH LEBIH AFDAL",
  "Pengajaran Hadis",
  "PENYERTAAN WANITA DALAM SOLAT JENAZAH",
  "(Riwayat Muslim)",
  "Pengajaran Hadis",
  "SOLAT JENAZAH DI KUBUR",
  "Pengajaran Hadis",
  "SOLAT GHAIB",
  "Pengajaran Hadis",
  "Waktu Solat Ghaib",
  "RUKUN SOLAT",
  "LAFAZ NIAT",
  "KEDUDUKAN IMAM SOLAT JENAZAH",
  "Daripada Nafi Abu Ghalib berkata:",
  "Situasi Solat Jenazah",
  "Rajah · Solat Jenazah",
  "TAKBIR PERTAMA",
  "TAKBIR KEDUA",
  "TAKBIR KETIGA",
  "TAKBIR KETIGA",
  "TAKBIR KEEMPAT",
  "SOLAT KETIKA JENAZAH RAMAI",
  "Pengajaran Hadis",
  "Rajah · Solat Jenazah",
  "Rajah · Solat Jenazah",
  "Rajah · Solat Jenazah",
  "Rajah · Solat Jenazah",
  "KEBUMI JENAZAH",
  "Pengajaran Hadis",
  "ISU PENANGGUHAN KEBUMI",
  "(Rujuk Faydh al-Qadir Syarh al-Jami’ al-Saghir, 3:377)",
  "DIKEBUMIKAN DI TEMPAT LAIN",
  "(Rujuk ‘Aun al-Ma’bud Syarh Sunan Abi Daud, 5:59)",
  "JENIS KUBUR",
  "HUKUM PEREMPUAN MENGIRINGI JENAZAH KE KUBUR",
  "makruh tahrim",
  "MENGHIMPUNKAN BEBERAPA JENAZAH DALAM SATU KUBUR",
  "Syarat",
  "Rajah · Pengebumian",
  "PENYEDIAAN TANAH KUBUR",
  "KAEDAH MENURUNKAN JENAZAH KE DALAM KUBUR",
  "3. Letakkan Jenazah dengan Lembut",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "Rajah · Pengebumian",
  "BUKA IKATAN JENAZAH",
  "BUKA KAIN KAFAN PADA MUKA JENAZAH",
  "TALKIN - TAZKIRAH",
  "(pengurusan jenazah), lalu Baginda mengambil sesuatu dan mencucuk-cucuk tanah",
  "TALKIN - TAZKIRAH",
  "HUKUM MEMBUAT BINAAN DI ATAS KUBUR",
  "Makruh tahrim",
  "Makruh tahrim (makruh yang menghampiri har",
  "UCAPAN TAKZIAH",
  "Rajah · Talkin & Takziah",
  "Rajah · Talkin & Takziah",
  "TAHLIL",
  "Mishkat al-Masabih 1907",
  "ISU PAHALA TAHLIL SAMPAI KEPADA SIMATI?",
  "Beliau berhujah dengan firman Allah SWT:",
  "IDDAH KERANA KEMATIAN SUAMI (IHDAD / BERKABUNG)",
  "IDDAH KERANA KEMATIAN SUAMI (IHDAD / BERKABUNG)",
  "TIDAK BOLEH KELUAR",
  "Adakah Wanita Dalam Iddah Kematian Suami",
  "Menjaga syarat yang pertama",
  "Dibenarkan dengan syarat berkabung di rumah anak.",
  "Nas & Dalil",
  "Jabatan Agama Islam Wilayah Persekutuan (JAWI)",
];

export const CHAPTERS = [
  { nama: "Pembukaan", mula: 0 },
  { nama: "Mandi Jenazah", mula: 3 },
  { nama: "Kafan", mula: 30 },
  { nama: "Solat Jenazah", mula: 52 },
  { nama: "Pengebumian", mula: 82 },
  { nama: "Talkin & Takziah", mula: 110 },
  { nama: "Tahlil", mula: 119 },
  { nama: "Iddah", mula: 123 },
  { nama: "Penutup", mula: 129 },
];

/** Slaid penuh 2560px — untuk paparan & zoom. */
export const src = (i: number) => `/slide/pengurusan-jenazah-2026/s${String(i).padStart(3, "0")}.webp`;
/** Thumbnail 400px — untuk grid lompat slaid. */
export const thumb = (i: number) => `/slide/pengurusan-jenazah-2026/thumb/t${String(i).padStart(3, "0")}.webp`;

/** Indeks bab bagi sesuatu slaid (untuk sorot bab aktif). */
export const babBagiSlaid = (i: number) => {
  let k = 0;
  for (let j = 0; j < CHAPTERS.length; j++) if (i >= CHAPTERS[j].mula) k = j;
  return k;
};
