/* Slaid "Penyembelihan Halal" — modul latihan PERKIB (Mohd Jabal B Abdul Rahim).
   Setiap slaid dirender daripada deck asal (1920×1080 → webp) supaya paparan
   KEKAL SAMA seperti fail asal. Animasi galaxy/3D ialah pembalut sahaja. */

export const SLIDE_COUNT = 60;

export const TAJUK: string[] = [
  "Penyembelihan Halal — Modul Latihan PERKIB",
  "Objektif Program",
  "Pengenalan — Surah Al-Ma'idah 5:3",
  "Hukum Menyembelih",
  "Bahagian Satu — Rukun Sembelihan",
  "Rukun 01 — Penyembelih",
  "Rukun 02 — Alat Sembelihan",
  "Dalil — Alat Sembelihan (Riwayat Muslim)",
  "Rukun 03 — Definisi Proses Penyembelihan",
  "Perlaksanaan — Empat Kaedah",
  "Kaedah 01 — الذبح (Al-Zabh)",
  "Kaedah 02 — النحر (Al-Nahr)",
  "النحر — Kedudukan Labbah",
  "Rujukan Visual",
  "Syarat Sembelihan (Proses)",
  "Kalimah Sembelihan",
  "Anatomi Leher",
  "Rujukan Visual — Kawasan Sembelihan",
  "Rujukan Visual",
  "Kawasan Penyembelihan Lembu",
  "Anatomi — Istilah",
  "Keratan Rentas Leher Ayam",
  "Rujukan Visual — Anatomi",
  "Amali — Kedudukan Sembelihan",
  "Amali — Teknik",
  "Amali — Sembelihan Ayam",
  "Amali — Perbandingan",
  "Amali — Rumah Sembelih",
  "Amali — Pengendalian",
  "Amali — Proses",
  "Rukun 04 — Haiwan Sembelihan",
  "Dua Keadaan — Haiwan Mampu Dikuasai",
  "Dua Keadaan — Haiwan Tidak Mampu Dikuasai",
  "Situasi Sembelihan",
  "Pemeriksaan Ayam",
  "Hikmah Sembelihan (1/2)",
  "Hikmah Sembelihan (2/2)",
  "Kajian Sains (1/5) — Latar Kajian",
  "Kajian Sains (2/5) — Metodologi",
  "Kajian Sains (3/5) — Hasil Syarak",
  "Kajian Sains (4/5) — Selepas Enam Saat",
  "Kajian Sains (5/5) — Electrical Stunning",
  "Ehsan Dalam Penyembelihan",
  "Bahagian Dua — Sunat, Makruh & Haram",
  "Perkara Sunat (1/2)",
  "Perkara Sunat (2/2)",
  "Perkara Makruh (1/2)",
  "Perkara Makruh (2/2)",
  "Perkara Haram",
  "Bahagian Tiga — Hukum Berkaitan Sembelihan",
  "Sembelihan Menggunakan Batu (1/2)",
  "Sembelihan Menggunakan Batu (2/2)",
  "Hukum Janin (1/2)",
  "Hukum Janin (2/2)",
  "Hukum Penggunaan Stunning — Fatwa Kebangsaan",
  "Senarai Fatwa",
  "Fatwa Thoracic Sticking (1/2)",
  "Fatwa Thoracic Sticking (2/2)",
  "Kesimpulan",
  "Terima Kasih",
];

export const CHAPTERS = [
  { nama: "Pembukaan", mula: 0 },
  { nama: "Rukun", mula: 4 },
  { nama: "Anatomi & Amali", mula: 16 },
  { nama: "Haiwan & Situasi", mula: 30 },
  { nama: "Hikmah & Sains", mula: 35 },
  { nama: "Adab", mula: 43 },
  { nama: "Hukum & Fatwa", mula: 49 },
  { nama: "Penutup", mula: 58 },
];

export const src = (i: number) => `/slide/sembelihan-2026/s${String(i).padStart(2, "0")}.webp`;
